### ISSUE TITLE
[GhostTotemFix] Task #66303 for GhostTotemFix v1.20 generated an exception

### ISSUE THREAD

**Issue by IAmStive222** [NebulaOX/Ghost-Totem-Fix#2]
[GhostTotemFix] Task #66303 for GhostTotemFix v1.20 generated an exception
java.lang.IllegalArgumentException: message cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:326) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:321) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.sendMessage(CraftPlayer.java:338) ~[paper-1.20.2.jar:git-Paper-318]
        at org.plugin.ghosttotemfix.GhostTotemFix$1.run(GhostTotemFix.java:48) ~[GhostTotemFix-1.20.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

what to do?

**Comment by IAmStive222** [comment]
by the way, after this mistake, people start having so-called "Ghost totem"

**Comment by IAmStive222** [comment]
and you also don't have any config.yml, please add it, because an error occurs in .jar file that it is not there, + it needs to be configured, but there is nothing there and the plugin does not work like that

**Comment by IAmStive222** [comment]
Well, in general, your plugin does not work, the guest totems are still there.
